#!/bin/sh
set -e
set -u

ENTRYPOINT=""

# Use script name (or eg. name of a symlink)
NAME="$(basename "$0")"

usage() {
    echo "usage: $0 <name>"
}

case "${NAME}"
    in
    envi)
        if [ "$#" -lt 1 ]
        then
            usage
            exit 1
        fi
        NAME="${1}"
        shift
        ENTRYPOINT="--entrypoint=/usr/bin/bash"
    ;;
    "")
        usage
        exit 1
    ;;
    *)
        # ok...
    ;;
esac

# TODO: Mount whole git project?
# TODO: Build image if not exists

IMAGE="envi.ypcs.fi/${NAME}:latest"
GIT_PARENT="$(git rev-parse --show-toplevel)"
ID="$(echo "${GIT_PARENT:-${PWD}}" |sha256sum |awk '{print $1}')"
_CACHEDIR="${XDG_CACHE_HOME:-${HOME}/.cache}"
CACHEDIR="${_CACHEDIR}/envi/${NAME}/${ID}"

mkdir -p "${CACHEDIR}"
echo "Using '${CACHEDIR}' as cache directory."

podman run \
    ${ENTRYPOINT} \
    --interactive \
    --rm \
    --tty \
    --userns=keep-id \
    --volume "${CACHEDIR}/cache:rw" \
    --volume "${CACHEDIR}:/home/user/.cache:rw" \
    --volume "${PWD}:${PWD}:rw" \
    --workdir "${PWD}" \
    "${IMAGE}" \
    "$@"
